# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('population_count', models.PositiveIntegerField(default=100)),
                ('infected_population', models.FloatField(default=40, verbose_name='Infected Population(%)')),
                ('simulation_iteration', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.IntegerField(default=0)),
                ('human_population', models.PositiveIntegerField()),
                ('new_zombies', models.IntegerField(default=0)),
                ('zombie_population', models.PositiveIntegerField(default=0)),
                ('panicked_human', models.PositiveIntegerField(default=0)),
                ('fighting_human', models.PositiveIntegerField(default=0)),
                ('zombie_killed', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zombie.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('userMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
